# Generated by Django 5.1.2 on 2024-10-30 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_celular_tiempo_de_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='tiempo_de_uso',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
